helm upgrade paceme ./helm \
  --namespace paceme \
  --create-namespace \
  --install \
  --set "oauth2.clientid=$(credstash get paceme/oauth2.clientid)" \
  --set "oauth2.secret=$(credstash get paceme/oauth2.secret)" \
  --set "oauth2.cookiesecret=$(credstash get paceme/oauth2.cookiesecret)" \
  --set "oauth2.userurl=https://auth.paceme.info/oauth2/userInfo" \
  --set "oauth2.authurl=https://auth.paceme.info/oauth2/authorize" \
  --set "oauth2.tokenurl=https://auth.paceme.info/oauth2/token" \
  --set "fitbit.clientId=$(credstash get paceme/fitbit-client-id)" \
  --set "fitbit.clientSecret=$(credstash get paceme/fitbit-client-secret)" \
  --set "api.postgrespw=$(credstash get paceme/postgrespw)" \
  --set "api.postgresconnectionstring=postgresql://paceme:$(credstash get paceme/postgrespw)@postgres.paceme.svc:5432/paceme" \
  --set "api.tag=$(cat api/package.json | jq -r '.version')" \
  --set "webapp.tag=$(cat webapp/package.json | jq -r '.version')" 