apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dashboard
  namespace: {{ .Release.Namespace }}
  name: dashboard
spec:
  replicas: {{ required "api.replicas is required" .Values.api.replicas }}
  selector:
    matchLabels:
      app: dashboard
  template:
    metadata:
      labels:
        app: dashboard
      namespace: {{ .Release.Namespace }}
      name: dashboard
    spec:
      containers:
        - name: dashboard
          image: {{ required "api.image is required" .Values.api.image }}:{{  required "api.tag is required" .Values.api.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: web
              containerPort: 8080
          env:
            - name: SECURE_USER_HEADER_ID
              value: x-auth-request-user
            {{ if .Values.api.fitbit.enabled }}
            - name: FITBIT_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: dashboard-fitbit
                  key: fitbit-client-id
            - name: FITBIT_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: dashboard-fitbit
                  key: fitbit-client-secret
            {{ end }}
            {{ if .Values.api.polar.enabled }}
            - name: POLAR_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: dashboard-polar
                  key: polar-client-id
            - name: POLAR_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: dashboard-polar
                  key: polar-client-secret
            {{ end }}
            - name: REDIS_PORT
              value: '6379'
            - name: REDIS_HOST
              value: dashboard-redis-service.{{ .Release.Namespace }}.svc
            {{ if .Values.api.ofd.enabled }}
            - name: OPEN_FOOD_DIARY_API
              value: http://{{ required "missing ofd config" .Values.api.ofd.host }}:{{ required "missing ofd config" .Values.api.ofd.port }}/api
            - name: OPEN_FOOD_DIARY_API_HEADER
              value: x-auth-request-user
            {{ end }}
            - name: CASSANDRA_CONTACT_POINTS
              value: {{ required "api.cassandra.contactpoints is required" .Values.api.cassandra.contactpoints }}
            - name: CASSANDRA_USER
              valueFrom:
                secretKeyRef:
                  name: {{ required "api.cassandra.credentialssecret is required" .Values.api.cassandra.credentialssecret }}
                  key: cassandrauser
            - name: CASSANDRA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ required "api.cassandra.credentialssecret is required" .Values.api.cassandra.credentialssecret }}
                  key: cassandrapassword