apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: paceme-api
  namespace: {{ .Release.Namespace }}
  name: paceme-api
spec:
  replicas: {{ required "api.replicas is required" .Values.api.replicas }}
  selector:
    matchLabels:
      app: paceme-api
  template:
    metadata:
      labels:
        app: paceme-api
      namespace: {{ .Release.Namespace }}
      name: paceme-api
    spec:
      containers:
        - name: paceme-api
          image: {{ required "api.image is required" .Values.api.image }}:{{  required "api.tag is required" .Values.api.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: web
              containerPort: 8080
          env:
            - name: SECURE_USER_HEADER_ID
              value: x-auth-request-user
            - name: FITBIT_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: paceme-api-secrets
                  key: fitbit-client-id
            - name: FITBIT_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: paceme-api-secrets
                  key: fitbit-client-secret
            - name: REDIS_PORT
              value: '6379'
            - name: REDIS_HOST
              value: redis-service.paceme.svc
            - name: PG_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: paceme-api-secrets
                  key: postgresconnectionstring