apiVersion: v1
kind: Secret
metadata:
  name: paceme-api-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  fitbit-client-id: {{ required "fitbit.clientId is required" .Values.fitbit.clientId | b64enc }}
  fitbit-client-secret: {{ required "fitbit.clientSecret is required" .Values.fitbit.clientSecret | b64enc }}
