apiVersion: v1
kind: Service
metadata:
  name: dashboard
  namespace: {{ .Release.Namespace }}
  labels:
    app: dashboard
spec:
  ports:
  - name: http
    port: 8081
    protocol: TCP
    targetPort: 8080
  selector:
    app: dashboard
  type: ClusterIP