api:
  image: ghcr.io/openhealthsuite/dashboard
  tag: v0.3.2
  replicas: 3
  cassandra:
    # expects a "cassandrauser" and "cassandrapassword" data key
    credentialssecret: cassandra-creds
    contactpoints: cassandra.service.svc:9042
  ofd:
    enabled: true
    host: openfooddiary.openhealthsuite.svc
    port: 3012
hostname: dashboard.openhealthsuite.com
