api:
  image: ghcr.io/openhealthsuite/dashboard
  tag: latest
  replicas: 3
  cassandra:
    # expects a "cassandrauser" and "cassandrapassword" data key
    credentialssecret: paceme-casscreds
    contactpoints: cassandra.service.svc:9042

hostname: app.paceme.info
