api:
  image: ghcr.io/openhealthsuite/dashboard
  tag: v0.3.2
  replicas: 3
  cassandra:
    # expects a "cassandrauser" and "cassandrapassword" data key
    credentialssecret: paceme-casscreds
    contactpoints: cassandra.service.svc:9042
  ofd:
    enabled: true
hostname: dashboard.openhealthsuite.com
