name: Build and Publish Dashboard Container

on:
  workflow_call:
    inputs:
      VERSION:
        type: string
        required: true
      PUSH:
        type: boolean
        default: false
        required: false
      PUSH_LATEST:
        type: boolean
        default: false
        required: false
      REPOSITORY:
        type: string
        required: false
        default: ghcr.io/openhealthsuite/dashboard
      PLATFORMS:
        type: string
        required: false
        default: linux/arm64/v8,linux/amd64

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GHCR
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Container image
        working-directory: .
        run: |
          sudo apt install qemu-user-static
          platarch=${{ inputs.PLATFORMS }}
          podman build --jobs=6 --platform=$platarch --manifest ${{ inputs.REPOSITORY }}:${{ inputs.VERSION }} .

      - name: Push Version
        if: ${{ inputs.PUSH }}
        run: | 
          podman manifest push ${{ inputs.REPOSITORY }}:${{ inputs.VERSION }} ${{ inputs.REPOSITORY }}:${{ github.sha }}
          podman manifest push ${{ inputs.REPOSITORY }}:${{ inputs.VERSION }} ${{ inputs.REPOSITORY }}:${{ inputs.VERSION }}

      - name: Push Latest
        if: ${{ inputs.PUSH && inputs.PUSH_LATEST }}
        run: |
          podman tag ${{ inputs.REPOSITORY }}:${{ inputs.VERSION }} ${{ inputs.REPOSITORY }}:latest
          podman manifest push ${{ inputs.REPOSITORY }}:latest ${{ inputs.REPOSITORY }}:latest
