name: Publish Dashboard Container

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-test-webapp:
    uses: ./.github/workflows/build_and_test_webapp.yml

  build-and-test-api:
    uses: ./.github/workflows/build_and_test_api.yml

  publish:
    needs:
      - build-and-test-webapp
      - build-and-test-api
    uses: ./.github/workflows/build_docker_image.yml
    with:
      VERSION: ${{ github.ref_name }}
      PUSH: true
      PUSH_LATEST: true

  publish-release:
    needs:
      - publish
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false